<?php

namespace App\Support\Payments;

use App\Models\ManualBank;
use App\Models\ManualPaymentRequest;
use App\Models\PaymentTransaction;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Log;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;


use Illuminate\Support\Str;


class PaymentLabelService
{

    private const WALLET_LABEL = 'المحفظة';


    /**
     * Resolve consistent gateway display information for a payment transaction.
     *
     * @return array{gateway_key: string|null, gateway_label: string|null, bank_name: string|null, channel_label: string|null, bank_label: string|null}
     * 
     *   
     */ 


    public static function forPaymentTransaction(PaymentTransaction $transaction): array

    {
        $transaction->loadMissing(['manualPaymentRequest.manualBank']);

        $data = self::normalizePayload([
            'payment_gateway' => $transaction->payment_gateway,
            'gateway_key' => $transaction->gateway_code ?? null,
            'gateway_code' => $transaction->gateway_code ?? null,
            'payment_gateway_name' => $transaction->payment_gateway_name ?? null,
            'gateway_display' => $transaction->getRawOriginal('gateway_label') ?? null,
            'channel_label' => $transaction->getRawOriginal('channel_label') ?? null,
            'payment_gateway_label' => $transaction->getRawOriginal('payment_gateway_label') ?? null,
            'manual_payment_request_id' => $transaction->manual_payment_request_id,
            'transaction_meta' => $transaction->meta,
            'meta' => $transaction->meta,
            'manual_payment_request' => $transaction->manualPaymentRequest,
            'manual_bank' => optional($transaction->manualPaymentRequest)->manualBank,
        ]);

        return self::finalizeLabels($data);
    }

    /**
     * Resolve consistent gateway display information for a manual payment request model.
     *
     * @return array{gateway_key: string|null, gateway_label: string|null, bank_name: string|null, channel_label: string|null, bank_label: string|null}
     */
    public static function forManualPaymentRequest(ManualPaymentRequest $manualPaymentRequest): array


    {
        $manualPaymentRequest->loadMissing(['manualBank', 'paymentTransaction.manualPaymentRequest.manualBank']);


        $transaction = $manualPaymentRequest->relationLoaded('paymentTransaction')
            ? $manualPaymentRequest->paymentTransaction
            : null;

        $data = self::normalizePayload([
            'payment_gateway' => $manualPaymentRequest->payment_gateway ?? null,
            'gateway_key' => $manualPaymentRequest->gateway_key ?? null,
            'payment_gateway_name' => $manualPaymentRequest->gateway_name ?? null,
            'manual_payment_request_id' => $manualPaymentRequest->getKey(),
            'manual_payment_request' => $manualPaymentRequest,
            'manual_bank' => $manualPaymentRequest->manualBank,
            'meta' => $manualPaymentRequest->meta,
            'manual_bank_name' => $manualPaymentRequest->bank_name,
            'payment_transaction' => $transaction,
            'transaction_meta' => $transaction?->meta,
        ]);

        return self::finalizeLabels($data);
    }

    /**
     * Resolve gateway information for arbitrary payloads generated by other presenters/resources.
     *
     * @param  array|Arrayable  $payload
     * @return array{gateway_key: string|null, gateway_label: string|null, bank_name: string|null, channel_label: string|null, bank_label: string|null}
     */
    public static function forPayload(array|Arrayable $payload): array
    {
        if ($payload instanceof Arrayable) {
            $payload = $payload->toArray();
        }

        return self::finalizeLabels(self::normalizePayload($payload));
    }

    /**
     * Normalize incoming payloads into a structure the resolver understands.
     */
    private static function normalizePayload(array $payload): array
    {
        $normalized = [];

        foreach ($payload as $key => $value) {
            if ($value instanceof Model) {
                $normalized[$key] = $value;

                continue;
            
            }

            if ($value instanceof Arrayable) {
                $normalized[$key] = $value->toArray();

                continue;
            }

            $normalized[$key] = $value;
        }

        return $normalized;

    }


    public static function normalizeGateway(?string $gateway): ?string
    {
        if (! is_string($gateway)) {
            return null;
        }

        $canonical = ManualPaymentRequest::canonicalGateway($gateway);

        if ($canonical === null || trim($canonical) === '') {
            return null;
        }

        $normalized = Str::lower(trim($canonical));

        return match ($normalized) {
            'manual_banks' => 'manual_bank',
            'east_yemen_bank', 'bank_alsharq', 'bank_alsharq_bank' => 'bank_alsharq',
            default => $normalized,
        };
    }


    /**
     * @return array{gateway_key: string|null, gateway_label: string|null, bank_name: string|null, channel_label: string|null, bank_label: string|null}
     */
    private static function finalizeLabels(array $data): array
    
    {
        $gatewayKey = self::resolveGatewayKey($data);
        $bankName = self::resolveBankName($data, $gatewayKey);
        $gatewayLabel = self::resolveGatewayLabel($data, $gatewayKey, $bankName);

        return [
            'gateway_key' => $gatewayKey,
            'gateway_label' => $gatewayLabel,
            'bank_name' => $bankName,
            'channel_label' => $gatewayLabel,
            'bank_label' => $bankName,
        ];
    }

    private static function resolveGatewayKey(array $data): ?string

    {
        $candidates = self::stringCandidates($data, [
            'gateway_key',
            'gateway_code',
            'payment_gateway_canonical',
            'payment_gateway_normalized',
            'payment_gateway',
            'channel',
            'payment_method',
            'manual_payment_request.gateway_name',
            'manual_payment_request.gateway',
            'payment_transaction.payment_gateway',
        ]);


        foreach ($candidates as $candidate) {
            $normalized = self::normalizeGatewayKey($candidate);
            if ($normalized !== null) {
                return $normalized === 'manual_bank' ? 'manual_banks' : $normalized;
            }
        }

        if (data_get($data, 'manual_payment_request_id')) {
            return 'manual_banks';
        }

        return null;
    }

    private static function resolveGatewayLabel(array $data, ?string $gatewayKey, ?string $bankName): ?string
    {
        if ($gatewayKey === 'wallet') {
            return self::WALLET_LABEL;
        }

        if ($gatewayKey === 'manual_banks') {
            if ($bankName === null || $bankName === '') {
                Log::warning('Bank name missing for manual bank gateway label.', [
                    'manual_payment_request_id' => data_get($data, 'manual_payment_request_id'),
                ]);

                return ManualBank::defaultDisplayName();


            }
            return $bankName;
        }


        $candidates = array_merge(
            self::stringCandidates($data, [
                'gateway_label',
                'payment_gateway_label',
                'channel_label',
                'payment_gateway_name',
                'gateway_name',
                'manual_payment_request.gateway_name',
                'manual_payment_request.meta.gateway_display_name',
                'manual_payment_request.meta.gateway_name',
                'manual_payment_request.meta.manual.gateway_display_name',
                'manual_payment_request.meta.manual.gateway_name',
                'meta.gateway_display_name',
                'meta.gateway_name',
                'meta.manual.gateway_display_name',
                'meta.manual.gateway_name',
                'transaction_meta.gateway_display_name',
                'transaction_meta.gateway_name',
            ]),
            $bankName ? [$bankName] : []
        );


        foreach ($candidates as $candidate) {
            $trimmed = trim($candidate);

            if ($trimmed !== '') {
                return $trimmed;
            }
        }

        if ($gatewayKey !== null) {
            $fallback = Arr::get(self::gatewayDisplayMap(), $gatewayKey);
            if (is_string($fallback) && trim($fallback) !== '') {
                return trim($fallback);


            }
        }

        return null;
    }


    private static function resolveBankName(array $data, ?string $gatewayKey): ?string
    {
        $candidatePaths = [
            'bank_name',
            'manual_bank_name',
            'manual_bank.name',
            'manual_bank.bank_name',
            'manual_payment_request.bank_name',
            'manual_payment_request.manualBank.name',
            'manual_payment_request.manualBank.bank_name',
            'manual_payment_request.meta.bank.name',
            'manual_payment_request.meta.bank.bank_name',
            'manual_payment_request.meta.manual.bank.name',
            'manual_payment_request.meta.manual.bank.bank_name',
            'manual_payment_request.meta.manual_bank.name',
            'manual_payment_request.meta.manual_bank.bank_name',
            'manual_payment_request.meta.manual_payment_request.bank.name',
            'manual_payment_request.meta.manual_payment_request.manual_bank.name',
            'meta.manual_bank.name',
            'meta.manual_bank.bank_name',
            'meta.manual.bank.name',
            'meta.manual.bank.bank_name',
            'meta.payload.bank.name',
            'meta.payload.bank_name',
            'meta.payload.manual_bank_name',
            'meta.bank.name',
            'meta.bank.bank_name',
            'transaction_meta.manual_bank.name',
            'transaction_meta.manual_bank.bank_name',
            'transaction_meta.manual.bank.name',
            'transaction_meta.manual.bank.bank_name',
            'transaction_meta.payload.bank.name',
            'transaction_meta.payload.bank_name',
            'transaction_meta.bank.name',
            'transaction_meta.bank.bank_name',
        ];

        foreach ($candidatePaths as $path) {
            $value = data_get($data, $path);

            if (is_string($value) && trim($value) !== '') {
                return trim($value);
            }
        }

        if ($gatewayKey === 'manual_banks') {
            if (data_get($data, 'manual_payment_request_id')) {
                $manualPaymentRequestId = (int) data_get($data, 'manual_payment_request_id');

            $manualBankColumns = ManualBank::relationSelectColumns();

                $manualPaymentRequest = ManualPaymentRequest::query()
                    ->with([
                        'manualBank' => static function (Builder $query) use ($manualBankColumns): void {
                            $query->select($manualBankColumns);
                        },
                    ])
                    ->find($manualPaymentRequestId);

                if ($manualPaymentRequest instanceof ManualPaymentRequest) {
                    $manualPaymentRequest->loadMissing('manualBank');

                    $candidate = $manualPaymentRequest->manualBank?->name
                        ?? $manualPaymentRequest->manualBank?->bank_name;

                    if (is_string($candidate) && trim($candidate) !== '') {
                        return trim($candidate);
                    }
                }
            }

            $manualBankId = self::resolveManualBankId($data);



            if ($manualBankId !== null) {
                $manualBankColumns = ManualBank::relationSelectColumns();

                $manualBank = ManualBank::query()
                    ->select($manualBankColumns)
                    ->find($manualBankId);

                if ($manualBank instanceof ManualBank) {
                    $candidate = $manualBank->name ?? $manualBank->bank_name;

                    if (is_string($candidate) && trim($candidate) !== '') {
                        return trim($candidate);
                    }
                }
            }
              return ManualBank::defaultDisplayName();

        }

        return null;
    }

    private static function resolveManualBankId(array $data): ?int
    {
        $candidatePaths = [
            'manual_bank_id',
            'manual_bank.id',
            'manual_bank.manual_bank_id',
            'manual_payment_request.manual_bank_id',
            'manual_payment_request.manual_bank.id',
            'manual_payment_request.manual_bank.manual_bank_id',
            'manual_payment_request.manualBank.id',
            'manual_payment_request.manualBank.manual_bank_id',
            'manual_payment_request.meta.manual_bank_id',
            'manual_payment_request.meta.manual_bank.id',
            'manual_payment_request.meta.manual_bank.manual_bank_id',
            'manual_payment_request.meta.manual_payment_request.manual_bank_id',
            'manual_payment_request.meta.manual_payment_request.manual_bank.id',
            'manual_payment_request.meta.manual_payment_request.manual_bank.manual_bank_id',
            'meta.manual_bank_id',
            'meta.manual_bank.id',
            'meta.manual_bank.manual_bank_id',
            'meta.manual.bank_id',
            'meta.manual.bank.id',
            'meta.manual.bank.manual_bank_id',
            'meta.payload.manual_bank_id',
            'meta.payload.manual_bank.id',
            'meta.payload.manual_bank.manual_bank_id',
            'meta.bank_id',
            'meta.bank.id',
            'meta.bank.manual_bank_id',
            'transaction_meta.manual_bank_id',
            'transaction_meta.manual_bank.id',
            'transaction_meta.manual_bank.manual_bank_id',
            'transaction_meta.manual.bank_id',
            'transaction_meta.manual.bank.id',
            'transaction_meta.manual.bank.manual_bank_id',
            'transaction_meta.payload.manual_bank_id',
            'transaction_meta.payload.manual_bank.id',
            'transaction_meta.payload.manual_bank.manual_bank_id',
        ];

        foreach ($candidatePaths as $path) {
            $value = data_get($data, $path);

            if (is_numeric($value)) {
                $normalized = (int) $value;

                if ($normalized > 0) {
                    return $normalized;
                }
            }
        }

        return null;
    }

    private static function normalizeGatewayKey(?string $gateway): ?string
    {
        if (! is_string($gateway)) {
            return null;
        }

        $trimmed = trim($gateway);

        if ($trimmed === '') {
            return null;
        }

        $canonical = ManualPaymentRequest::canonicalGateway($trimmed);

        if ($canonical !== null && $canonical !== '') {
            return Str::lower($canonical);
        }

        return Str::lower($trimmed);
    }

    /**
     * @return array<int, string>
     */
    private static function stringCandidates(array $data, array $paths): array
    
    {
        $values = [];


        foreach ($paths as $path) {
            $value = data_get($data, $path);

            if (is_string($value) && trim($value) !== '') {
                $values[] = trim($value);
            }
        }

        return $values;
    }

    /**
     * @return array<string, string>
     */
    private static function gatewayDisplayMap(): array
    {
        return [
            'wallet' => self::WALLET_LABEL,
            'east_yemen_bank' => 'East Yemen Bank',
            'cash' => 'Cash',
        ];
    }

}
